In [1]:
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTENC

In [2]:
df=pd.read_csv( r"C:\Users\rosha\Desktop\ds\project roshaan\AD.csv")
df.head()

,PatientID,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,...,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis,DoctorInCharge
0,4751,73,0,0,2,22.927749,0,13.297218,6.327112,1.347214,...,0,0,1.725883,0,0,0,1,0,0,XXXConfid
1,4752,89,0,0,0,26.827681,0,4.542524,7.619885,0.518767,...,0,0,2.592424,0,0,0,0,1,0,XXXConfid
2,4753,73,0,3,1,17.795882,0,19.555085,7.844988,1.826335,...,0,0,7.119548,0,1,0,1,0,0,XXXConfid
3,4754,74,1,0,1,33.800817,1,12.209266,8.428001,7.435604,...,0,1,6.481226,0,0,0,0,0,0,XXXConfid
4,4755,89,0,0,0,20.716974,0,18.454356,6.310461,0.795498,...,0,0,0.014691,0,0,1,1,0,0,XXXConfid

In [3]:
df.drop(["PatientID", "DoctorInCharge"], axis=1, inplace=True, errors='ignore')

In [4]:
numerical_cols = ["Age", "BMI", "AlcoholConsumption", "PhysicalActivity", "DietQuality", 
                      "SleepQuality", "SystolicBP", "DiastolicBP", "CholesterolTotal", 
                      "CholesterolLDL", "CholesterolHDL", "CholesterolTriglycerides",
                      "MMSE", "FunctionalAssessment", "ADL"]
    
categorical_cols = [c for c in df.columns if c not in numerical_cols and c != "Diagnosis"]

In [5]:
scaler = StandardScaler()
num_existing = [c for c in numerical_cols if c in df.columns]
df[num_existing] = scaler.fit_transform(df[num_existing])

In [6]:
categories = [sorted(df['Ethnicity'].unique().tolist()), sorted(df['EducationLevel'].unique().tolist())]
encoder = OrdinalEncoder(categories=categories)
df[['Ethnicity', 'EducationLevel']] = encoder.fit_transform(df[['Ethnicity', 'EducationLevel']])

In [7]:
x = df.drop("Diagnosis", axis=1)
y = df.Diagnosis
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.1, random_state=42)

In [8]:
cat_indices = [x.columns.get_loc(col) for col in categorical_cols if col in x.columns]
smote = SMOTENC(categorical_features=cat_indices, random_state=42)
x_res, y_res = smote.fit_resample(x_train, y_train)

In [9]:
modelbest_decision1=DecisionTreeClassifier(criterion="entropy",max_depth=5,max_features=None,min_samples_leaf=4,min_samples_split=2,random_state=42)

In [10]:
bagg_best=BaggingClassifier(estimator=modelbest_decision1,n_estimators=100,max_samples=0.7,max_features=1.0,bootstrap=True,bootstrap_features=False,random_state=42)
model=bagg_best.fit(x_res,y_res)

In [11]:
model.score(x_test,y_test)

0.958139534883721

In [12]:
joblib.dump(model, "model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(x.columns.tolist(), "feature_columns.pkl")
joblib.dump(num_existing, "numerical_features.pkl")
joblib.dump(categorical_cols, "categorical_features.pkl")

print("✅ Model saved successfully!")

✅ Model saved successfully!

In [13]:
print(scaler)

StandardScaler()

In [14]:
print(hasattr(scaler, "mean_"))

True

In [15]:
print(type(scaler))
print(hasattr(scaler, "mean_"))
print(hasattr(scaler, "scale_"))
print(hasattr(scaler, "n_features_in_"))

print(scaler.mean_[:5])

<class 'sklearn.preprocessing._data.StandardScaler'>
True
True
True
[74.90879479 27.65569691 10.03944171  4.92020214  4.99313791]

In [16]:
import sklearn
print(sklearn.__version__)

1.8.0

In [20]:
print("Scaler features:", scaler.n_features_in_)
print("Input features:", len(num_existing))
print(num_existing)
print(df[num_existing].shape)

Scaler features: 15
Input features: 15
['Age', 'BMI', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality', 'SleepQuality', 'SystolicBP', 'DiastolicBP', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL', 'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment', 'ADL']
(2149, 15)

In [ ]:
print(scaler.__dict__.keys())

In [21]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [28]:
df

,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,FamilyHistoryAlzheimers,CardiovascularDisease,Diabetes,Depression,HeadInjury,Hypertension,SystolicBP,DiastolicBP,CholesterolTotal,CholesterolLDL,CholesterolHDL,CholesterolTriglycerides,MMSE,FunctionalAssessment,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis
0,-0.212368,0,0.0,2.0,-0.655225,0,0.565923,0.492525,-1.253593,1.119918,0,0,1,1,0,0,0.298159,-1.014750,0.403677,-1.572661,-1.114429,-0.648199,0.779037,0.497506,0,0,-1.104434,0,0,0,1,0,0
1,1.567757,0,0.0,0.0,-0.114751,0,-0.954895,0.945093,-1.538442,0.056836,0,0,0,0,0,0,-0.742572,-1.469595,0.140248,1.593119,0.845730,0.650721,0.680297,0.704907,0,0,-0.810601,0,0,0,0,1,0
2,-0.212368,0,3.0,1.0,-1.366428,0,1.653006,1.023896,-1.088855,1.487380,1,0,0,0,0,0,-1.359301,1.486898,1.386812,0.668569,0.445615,-1.418585,-0.859222,0.281813,0,0,0.724491,0,1,0,1,0,0
3,-0.101111,1,0.0,1.0,0.851625,1,0.376930,1.227995,0.839804,0.760833,0,0,0,0,0,0,-0.626935,1.430043,-1.542715,-1.360103,0.388780,0.483468,-0.088723,1.343346,0,1,0.508044,0,0,0,0,0,0
4,1.567757,0,0.0,0.0,-0.961607,0,1.461793,0.486696,-1.443293,-0.824566,0,0,0,0,0,0,-1.552029,1.543754,0.291653,-0.725756,-0.111924,0.617060,-0.143712,0.333665,0,0,-1.684679,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,-1.547463,0,0.0,1.0,1.589030,0,-1.472807,-0.304649,0.537127,0.274767,0,0,0,0,0,0,-0.472753,0.634063,1.299701,-0.679609,0.063957,0.061185,-1.574000,-1.674022,0,0,-0.166194,1,0,0,0,0,1
2145,0.010147,0,0.0,2.0,-1.357833,0,1.516149,-1.246106,-0.718090,0.853112,0,0,0,0,0,0,0.683615,0.918342,-0.912555,-0.667149,1.477761,1.370158,-0.963527,1.247350,0,1,1.431627,0,0,0,0,0,1
2146,0.232663,0,0.0,1.0,-1.687864,0,-0.945836,1.738405,1.075131,-0.726886,0,0,0,0,0,0,-0.742572,1.600609,0.278072,0.736484,1.738352,0.652402,0.261971,-1.074634,0,0,0.018099,0,0,0,0,0,1
2147,0.343921,1,3.0,1.0,-1.712334,0,-0.237109,0.502036,-1.282402,0.721313,0,1,0,0,0,0,-1.205119,0.349785,0.399688,-1.657260,0.943104,-0.814293,-1.245437,0.032446,0,0,-0.406078,0,0,0,0,1,1
2148,-0.323626,0,0.0,2.0,0.780797,0,-0.373267,0.577902,1.013715,1.603726,0,0,0,0,0,0,1.223253,-0.673616,1.368354,-0.741201,0.970723,-0.106751,-0.422749,0.424432,0,1,1.134115,0,1,0,0,1,0

In [23]:
x_test

,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,FamilyHistoryAlzheimers,CardiovascularDisease,Diabetes,Depression,HeadInjury,Hypertension,SystolicBP,DiastolicBP,CholesterolTotal,CholesterolLDL,CholesterolHDL,CholesterolTriglycerides,MMSE,FunctionalAssessment,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness
1159,1.456499,1,1.0,0.0,-0.182135,0,1.347056,-1.366735,0.245805,1.289692,0,0,0,0,0,0,1.608708,-0.730472,-0.335004,-1.527463,1.608829,-0.211333,-0.030947,0.770312,0,0,0.616375,1,0,0,0,1
1822,0.121405,0,1.0,2.0,0.463200,1,-0.901800,-1.590189,-0.558986,0.466153,0,0,1,1,0,0,1.608708,1.486898,1.528209,-0.405828,1.589301,1.307896,-0.064393,-0.660107,0,0,0.815537,0,0,0,0,1
978,-0.212368,0,0.0,1.0,-1.191147,0,1.656915,1.529823,0.399671,0.806419,0,0,0,0,0,0,0.991979,-0.389338,1.700063,1.462797,1.205502,-0.722410,-0.457999,1.360144,1,0,0.401251,0,0,0,1,1
759,0.232663,1,0.0,3.0,1.210719,1,-1.657380,0.945509,1.257288,0.900854,0,0,1,0,0,0,0.105431,1.657465,0.837815,1.687006,-0.317451,0.471201,-0.210375,0.949768,0,0,-0.617767,1,0,0,0,0
874,-0.434884,0,1.0,0.0,1.612613,1,1.409280,-1.692688,-1.411373,0.424336,1,0,0,1,0,1,-1.282210,0.918342,-0.625658,-0.947734,0.422783,0.084442,1.691800,1.267683,0,0,0.362071,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,1.679015,1,3.0,1.0,-0.302580,1,-1.216661,1.750867,-1.466213,-0.934510,0,0,0,0,1,0,-0.395662,0.634063,-0.157097,-1.312331,0.799881,-0.772396,-1.684480,0.912864,1,0,0.725471,0,0,0,0,0
2005,-0.212368,1,1.0,3.0,-0.284334,1,-1.002101,1.118054,-0.911848,1.497661,1,0,0,0,0,1,-1.282210,0.577208,0.529065,0.723584,-1.621075,-1.471258,0.288448,1.060376,0,0,1.401477,0,0,1,0,1
2117,1.567757,1,1.0,1.0,-0.161462,0,1.632188,-0.374580,1.560783,-1.048035,1,0,0,0,0,0,-0.935300,-0.105060,-0.528116,0.298711,0.391209,-1.460878,-0.159583,-0.276782,1,0,-0.123494,0,1,0,0,0
1029,1.345242,1,0.0,2.0,-1.285683,0,-0.945758,-1.014467,1.324243,0.532991,0,0,0,0,0,0,1.685800,0.975197,-0.678287,0.377509,0.281597,0.118620,-0.806856,-0.516479,0,0,-1.580900,0,0,0,0,0
1676,1.679015,1,0.0,1.0,-1.680551,1,-0.015726,0.223214,1.486957,1.435174,1,0,0,0,0,0,0.645069,0.861486,0.715944,0.465903,0.379979,-0.647011,0.453569,-1.364306,0,0,0.505752,1,1,0,0,1